export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  portalOwnerAccessToken: process.env.PORTAL_OWNER_ACCESS_TOKEN ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  awsSessionToken: process.env.AWS_SESSION_TOKEN ?? "",
  localLlmBaseUrl: process.env.LOCAL_LLM_BASE_URL ?? "",
  localLlmRuntime: process.env.LOCAL_LLM_RUNTIME ?? "",
  localLlmModel: process.env.LOCAL_LLM_MODEL ?? "",
  localLlmApiKey: process.env.LOCAL_LLM_API_KEY ?? "",
  localLlmMaxTokens: Number(process.env.LOCAL_LLM_MAX_TOKENS ?? 4096),
  localLlmTemperature: Number(process.env.LOCAL_LLM_TEMPERATURE ?? 0.1),
  localLlmTopP: Number(process.env.LOCAL_LLM_TOP_P ?? 0.9),
  localLlmTimeoutMs: Number(process.env.LOCAL_LLM_TIMEOUT_MS ?? 60000),
  portalS3Bucket: process.env.PORTAL_S3_BUCKET ?? "",
  portalS3Region: process.env.PORTAL_S3_REGION ?? "",
};
